# Global Configuration


# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  prefix: '[gin_micro_service]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  #addr: '192.168.0.73:6379'
  addr:  '47.106.89.198:6379'
  password: 'root@ztgd'


# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 7777
  db-type: 'mysql'

mysql:
  #正式服务器
  #path: 47.107.229.161
  #path: 192.168.0.73
  #测试服务器
  path: 47.106.89.198
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: finance_center
  db-name-order: order_center
  db-name-customer: customer_center
  username: root
  password: root@ztgd
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false


# aliyun oss configuration
aliyun-oss:
  endpoint: 'yourEndpoint'
  access-key-id: 'yourAccessKeyId'
  access-key-secret: 'yourAccessKeySecret'
  bucket-name: 'yourBucketName'
  bucket-url: 'yourBucketUrl'
  base-path: 'yourBasePath'


# excel configuration
excel:
  dir: './resource/excel/'


#nacos
nacos:
  register-ip: "127.0.0.1"  #微服务的ip
  register-port: 8886        #微服务的port， 这个配置项用不着，一般读取system里面的addr
  register-servicename: "finance-service" #微服务的服务名称
  #测试环境
  nacos-ip: "47.106.89.198"     #nacos 地址
  #生产环境
  #nacos-ip: "47.107.229.161"
  #nacos-ip: "192.168.0.73"
  nacos-port: 8848          #nacos 端口
  nacos-username: "nacos"
  nacos-password: "nacos"
  nacos-logdir: "log" #nacos 日志存放路径